[options]
Architecture = auto
CacheDir = /var/cache/pacman/pkg/
Color
ILoveCandy
CheckSpace
ParallelDownloads = 10
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
XferCommand = /usr/bin/curl -L -C - -f -o %o %u --retry 3 --retry-delay 3

# --- VeloxOS Main Repos ---
[veloxos-core]
SigLevel = PackageOptional TrustedOnly
Server = https://downloads.veloxos.org/repos/stable/core

[veloxos-v3]
SigLevel = PackageOptional TrustedOnly
Server = https://downloads.veloxos.org/repos/stable/v3

[veloxos-v4]
SigLevel = PackageOptional TrustedOnly
Server = https://downloads.veloxos.org/repos/stable/v4


