[veloxos-core]
SigLevel = PackageOptional TrustedOnly
Server = https://downloads.veloxos.org/repos/stable/core

[veloxos-v3]
SigLevel = PackageOptional TrustedOnly
Server = https://downloads.veloxos.org/repos/stable/v3

[veloxos-v4]
SigLevel = PackageOptional TrustedOnly
Server = https://downloads.veloxos.org/repos/stable/v4
