target_branch=stable
cache_dir=/var/cache/manjaro-tools
chroots_dir=/var/lib/manjaro-tools
branch=master
iso_profiles_dir=/home/user/veloxos-build
run_dir=/home/user/veloxos-build
iso_dir=/var/cache/manjaro-tools/iso
pacman_conf="/home/user/veloxos-build/custom/kde/pacman-default.conf"
default_conf=""
pky=("veloxos")
